name: Build and Deploy

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      WORKLOAD_IDENTITY_PROVIDER:
        required: true
      SERVICE_ACCOUNT_EMAIL:
        required: true
      PROJECT_ID:
        required: true

permissions:
  id-token: write
  contents: read

concurrency:
  group: ${{ inputs.environment }}
  cancel-in-progress: true

jobs:
  build:
    name: ${{ inputs.environment }} - Build and Deploy
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env:
      NODE_ENV: production

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0.4.0'
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: terraform init
        working-directory: terraform
        run: |
          terraform init --var="project_id=${{ secrets.PROJECT_ID }}"

      - name: terraform apply (API Services)
        working-directory: terraform
        run: |
          terraform apply -auto-approve -target=google_project_service.services --var="project_id=${{ secrets.PROJECT_ID }}" --var="run_id=${{ github.run_number }}"

      - name: terraform apply (Artifact)
        working-directory: terraform
        run: |
          terraform apply -auto-approve -target=google_artifact_registry_repository.google_artifact_registry_repository --var="project_id=${{ secrets.PROJECT_ID }}" --var="run_id=${{ github.run_number }}"

      - name: Build Container
        run: |
          docker build -t europe-west2-docker.pkg.dev/${{ secrets.PROJECT_ID }}/bookings-docker-repo/bookings-app:${{github.run_number}} .
          gcloud auth configure-docker europe-west2-docker.pkg.dev
          docker push europe-west2-docker.pkg.dev/${{ secrets.PROJECT_ID }}/bookings-docker-repo/bookings-app:${{github.run_number}}

      - name: terraform apply
        working-directory: terraform
        run: |
          terraform apply -auto-approve --var="project_id=${{ secrets.PROJECT_ID }}" --var="run_id=${{ github.run_number }}"
